------------------------------------------------------------------------------------------------------<br>
<h3 style="background:#87a1c2; color:#ffffff; padding:20px; border-radius:5px;">✍ EJERCICIOS NUMPY PARA @EGGERS</h3><br>
------------------------------------------------------------------------------------------------------<br>

1. Crea un vector entre 7 y 66.
2. Invierte el vector generado anteriormente.
3. Matriz de 4x4 con valores entre 0 y 15.
5. Crea la matriz identidad de 5x5.
6. Crea una matriz de 5x5 donde la posición central y todas las posiciones que conforman el marco valgan 1 y el resto 0.
7. Matriz de 4x4 donde cada fila valga entre 3 y 0. Valores in crescendo.
8. Crea un array de ceros de 2x7.
9. Crea un array de ceros de 5x4 excepto toda la primera fila que valga 1.
10. Crea un array que represente una tabla de ajedrez. Negras 1 y blancas 0.

In [2]:
#Importar la libreria

import numpy as np

In [4]:
#1. Crea un vector entre 7 y 66

vector = np.arange(7,67)
vector

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23,
       24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
       41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57,
       58, 59, 60, 61, 62, 63, 64, 65, 66])

In [5]:
#2. Invierte el vector generado anteriormente.
#metodo 1
vector_invertido = vector[::-1]
vector_invertido

array([66, 65, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50,
       49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7])

In [7]:
#Metodo2
Vector_invert_np = np.flip(vector)
Vector_invert_np

array([66, 65, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50,
       49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7])

In [92]:
#3. Matriz de 4x4 con valores entre 0 y 15.
relleno = np.random.randint(0,15,(4,4))
relleno


array([[11, 13,  7,  2],
       [11, 13,  7,  9],
       [ 8,  9,  1,  2],
       [ 9, 11,  2,  3]])

In [21]:
#5. Crea la matriz identidad de 5x5.
matriz_id = np.identity(5)
matriz_id

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [105]:
#6. Crea una matriz de 5x5 donde la posición central y todas las posiciones que conforman el marco valgan 1 y el resto 0.
matriz_ojo= np.zeros((5,5))
matriz_ojo[0::4] += np.ones(5)
matriz_ojo[1:4,0] += 1
matriz_ojo[2,2] += 1
matriz_ojo[1:4,4] += 1
matriz_ojo



array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 1., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [91]:
#7. Matriz de 4x4 donde cada fila valga entre 3 y 0. Valores in crescendo.
m_crescendo=np.zeros((4,4))
m_crescendo[:,:]=np.random.randint(0,3,(4,4))
m_crescendo

array([[1., 0., 0., 2.],
       [1., 2., 1., 0.],
       [1., 2., 1., 2.],
       [2., 0., 1., 2.]])

In [23]:
#8. Crea un array de ceros de 2x7.
matriz_7=np.zeros((2,7))
matriz_7

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [49]:
#9. Crea un array de ceros de 5x4 excepto toda la primera fila que valga 1.
matriz_8=np.zeros((5,4))
matriz_8[0] += np.ones(4)
matriz_8

array([[1., 1., 1., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [95]:
#10. Crea un array que represente una tabla de ajedrez. Negras 1 y blancas 0.
ajedrez = np.zeros((8,8))
ajedrez[0::2,0::2] += 1 
ajedrez[1::2,1::2] += 1
ajedrez

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])